### ISSUE TITLE
tf.unpack is deprecated

### ISSUE THREAD

**Issue by lisaannyu** [RobRomijnders/RNN_basketball#5]
Hello,

tf.unpack in model.py is deprecated, in favor of tf.unstack, which leads to an error.  This is easily fixable for the user, but I thought you should know.  Thanks!

**Comment by sealneaward** [comment]
This has been addressed in a PR that updates the code for tf 1.0

**Comment by sealneaward** [comment]
@RobRomijnders can you close this as well?
