### ISSUE TITLE
tf.nn.cell not a real function

### ISSUE THREAD

**Issue by lisaannyu** [RobRomijnders/RNN_basketball#6]
Hello again,

In line 56 of model.py, there is the line:
outputs, _ = tf.nn.rnn(cell, inputs, initial_state=initial_state)

To the best of my knowledge, tf.nn.rnn is not a real function.  What should it be instead?

Thanks!

**Comment by sealneaward** [comment]
It is not a function in the version of tensorflow that you are using, which I am assuming is >= 1.0.
The correct syntax for the new tensorflow is to use a static_rnn constructor instead.

```py
outputs, _ = tf.contrib.rnn.static_rnn(cell, inputs, initial_state=initial_state)
```

**Comment by RobRomijnders** [comment]
Thanks. You're right, it's old code. Back when rnn was in the contrib.

Could you make a pull request?

**Comment by sealneaward** [comment]
@RobRomijnders I created a [PR](https://github.com/RobRomijnders/RNN_basketball/pull/7).

**Comment by sealneaward** [comment]
@RobRomijnders can you close this issue?
